name: ${project.name}
version: ${project.version}
description: 'Plugin na Janusza'
author: 'TheMolkaPL <themolkapl@gmail.com>'
website: 'https://github.com/TheMolkaPL/Janusz'
main: pl.themolka.janusz.JanuszPlugin
api-version: '1.14'
load: startup

commands:
  closedoors:
    description: 'Zamknij wszystkie drzwi na załadowanych w tym świecie chunkach'
    permission: 'janusz.command.closedoors'
    usage: '/<command>'
  formatsign:
    description: 'Formatuj tabliczkę'
    permission: 'janusz.command.formatsign'
    usage: '/<command> <format> <value>'
  player:
    description: 'Informacje o danym graczu'
    aliases: ['gracz', 'seen', 'find']
    permission: 'janusz.command.player'
    usage: '/<command> [player]'
  replacesign:
    description: 'Podmień rodzaj tabliczki razem z jej zawartością'
    permission: 'janusz.command.replacesign'
    usage: '/<command> <material>'
  sex:
    description: 'Informacje o płci i jej zmiana'
    aliases: ['gender']
    permission: 'janusz.command.sex'
    usage: '<command> [sex]'

permissions:
  'janusz.*':
    description: 'Gives access to all Janusz permissions'
    default: op
  'janusz.command.*':
    description: 'Gives access to all Janusz commands'
    default: op
  'janusz.command.closedoors':
    description: 'Gives access to the /closedoors command'
    default: op
  'janusz.command.formatsign':
    description: 'Gives access to the /formatsign command'
    default: op
  'janusz.command.player':
    description: 'Gives access to the /player command'
    default: true
  'janusz.command.player.admin':
    description: 'Gives access to the /player command with admin information'
    default: op
  'janusz.command.player.show-all':
    description: 'Gives access to show all cached usernames in suggestions.'
    default: op
  'janusz.command.replacesign':
    description: 'Gives access to the /replacesign command.'
    default: op
  'janusz.command.sex':
    description: 'Gives access to the /sex command'
    default: true
  'janusz.command.sex.change':
    description: 'Gives access to the /sex <sex> command'
    default: true

  'janusz.colored-signs':
    description: 'Gives access to color signs'
    default: true
